### ISSUE TITLE
[Feature Request] Configurable/toggable EXP Repair Cost

### ISSUE THREAD

**Issue by Terminal-Access** [Flo56958/MineTinker#200]
As i understand right now the repair cost of say a pickaxe not only costs the materials but also experiance.

we are finding after a very short time the experiance cost just gets exponentially high and un payable.

could we have some options to configure this rate and or just an option to outright disable the xp cost.

e.g so that it only costs the materials to repair.

Sadly we have had to remove the plugin from our server in it's current state as it makes using tools very hard after a few hours of playing.

**Comment by Flo56958** [comment]
@Terminal-Access the exp-cost in vanilla is way to high for MT. There are two options:
- You can modify it to have Selfrepair or Photosynthesis so it repairs itself
- You can simply drop material in the inventory on the tool to repair it (diamond for diamond tool, wood for wood tool, etc)

The Plugin does not change the vanilla repair feature in any way or form due to compatibilities, and it was always designed to be free to modify.
