### ISSUE TITLE
[Exploit] Crafting unlimited items.

### ISSUE THREAD

**Issue by jacklollz2** [Flo56958/MineTinker#244]
**Describe the bug**
Unlimited amount of items can be crafted by players, when there is a stack of 2 or more.

**To Reproduce**
1) Have 2 regular (not MineTinker) swords, i.e Netherite Swords, in a stack.
2) Place the stack in your crafting to convert it to a MineTinker item.
3) Shift-click the newly converted item, and enjoy duped items.

**Expected behavior**
The whole stack being converted properly.

**Information about the server (please complete the following information):**
 - Plugin Version: 1.7.2
 - Server Version: git-Purpur-1970 (MC: 1.19.4)
 - Other Plugins: StackableItems https://dev.bukkit.org/projects/stackableitems

**Comment by Flo56958** [comment]
@jacklollz2 

I have looked into this problem. MineTinker does not change amounts of crafting items in the converting process. (Latest commit [bb8c1e3dde046eb809167a35e0fbdc4c85907eb3] made sure of this) So if such a plugin is installed MineTinker should behave compatible.

When i try to convert tools with stacked items the stacked items go up. I think it is very likely, that the stacking plugin you are using does not work well with this converting process (which is a special case of crafting) and therefore the bug happens. It will duplicate items even when clicking normally on the tool. A quick glance on the issue page of StackableItems seems to support that the duping problem is on their side.

You could try to contact the author of that plugin and explain the situation.

I will close this issue for now. If the bug is a problem of MineTinker, it can be reopened at a later time.
